models/Orders.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "orders".
 *
 * @property int $order_id
 * @property int $an
 * @property string $order_datetime
 * @property string|null $progress_note
 * @property string|null $order_oneday
 * @property string|null $order_continue
 * @property string|null $comment
 * @property int $user_id
 * @property int $ward_id
 * @property array|null $medication
 * @property string|null $record_i_o
 * @property string|null $record_vitalsign
 * @property string|null $food
 * @property string|null $is_lab
 * @property string|null $is_xray
 * @property array|null $progress
 * @property array|null $oneday_list
 */
class Orders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    public function behaviors()
    {
        return [
            [
                'class' => AttributeBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => 'medication',
                    ActiveRecord::EVENT_BEFORE_UPDATE => 'medication',
                ],
                'value' => function ($event) {                    
                    return $this->medication ? implode(',', $this->medication):$this->medication;
                },
            ],
            [
              'class' => AttributeBehavior::className(),
              'attributes' => [
                  ActiveRecord::EVENT_BEFORE_INSERT => 'progress',
                  ActiveRecord::EVENT_BEFORE_UPDATE => 'progress',
              ],
              'value' => function ($event) {                    
                  return $this->progress ? implode(',', $this->progress):$this->progress;
              },
            ],
            [
              'class' => AttributeBehavior::className(),
              'attributes' => [
                  ActiveRecord::EVENT_BEFORE_INSERT => 'oneday_list',
                  ActiveRecord::EVENT_BEFORE_UPDATE => 'oneday_list',
              ],
              'value' => function ($event) {                    
                return $this->oneday_list ? implode(',', $this->oneday_list):$this->oneday_list;
              },
            ],
    ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['an', 'user_id'], 'required'],
            [['an', 'user_id','ward_id'], 'integer'],
            [['order_datetime','medication','progress','oneday_list'], 'safe'],
            [['progress_note', 'order_oneday', 'order_continue', 'comment'], 'string'],
            [['record_i_o', 'food','record_vitalsign','is_lab','is_xray',], 'string', 'max' => 1],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'order_id' => 'Order ID',
            'an' => 'AN',
            'ward_id' => 'ward_id',
            'order_datetime' => 'วันเวลาที่บันทึก Order',
            'progress_note' => 'Progress Note เพิ่มเติม',
            'progress' => 'Progress Note',
            'oneday_list' => 'Order Oneday',
            'order_oneday' => 'Order One Day เพิ่ม',
            'order_continue' => 'Order เพิ่มเติม',
            'comment' => 'หมายเหตุ',
            'user_id' => 'ผู้บันทึก',
            'medication' => 'Medication',
            'record_i_o' => 'Record I/O',
            'record_vitalsign' => 'Record V/S',
            'food' => 'อาหาร',
            'is_lab' => 'สั่ง Lab',
            'is_xray' => 'สั่ง X-Ray',
        ];
    }

    public function medToArray()
    {
      return $this->medication = explode(',', $this->medication);
    }

    public function progressToArray()
    {
      return $this->progress = explode(',', $this->progress);
    }

    public function orderToArray()
    {
      return $this->oneday_list = explode(',', $this->oneday_list);
    }

    public function foodToArray()
    {
      return $this->food = explode(',', $this->food);
    }
    
    public static function itemsAlias($key){
        $items = [
          'med'=> ArrayHelper::map(StandingOrder::find()->all(), 'med_id', 'medicine'),
          'med_use' => ArrayHelper::map(StandingOrder::find()->where(['is_active' => '1'])->all(), 'med_id', 'medicine'),
          'prog'=> ArrayHelper::map(LProgress::find()->all(), 'progress_id', 'progress_name'),
          'prog_use' => ArrayHelper::map(LProgress::find()->where(['is_active' => '1'])->all(), 'progress_id', 'progress_name'),
          'oned'=> ArrayHelper::map(OrderOneday::find()->all(), 'order_id', 'order_name'),
          'oned_use' => ArrayHelper::map(OrderOneday::find()->where(['is_active' => '1'])->all(), 'order_id', 'order_name'),
          'group' => ArrayHelper::map(LOrderGroup::find()->all(), 'order_group_id', 'order_group_name'),
          'food' => [
            '1' => 'Regular Diet',
            '2' => 'Soft Diet',
          ]
        ];
        return ArrayHelper::getValue($items,$key,[]);
        //return array_key_exists($key, $items) ? $items[$key] : [];
    }
    
    public function getItemMed()
    {
      return self::itemsAlias('med');
    }

    public function getOrderMed()
    {
      return self::itemsAlias('med_use');
    }

    public function getItemProg()
    {
      return self::itemsAlias('prog');
    }

    public function getOrderProg()
    {
      return self::itemsAlias('prog_use');
    }

    public function getItemOrder()
    {
      return self::itemsAlias('oned');
    }

    public function getOrderOneday()
    {
      return self::itemsAlias('oned_use');
    }

    public function getItemGroup()
    {
      return self::itemsAlias('group');
    }

    public function getItemFood()
    {
      return self::itemsAlias('food');
    }

  public function getMedName(){
        $meds = $this->getItemMed();
        $medSelected = explode(',', $this->medication);
        $medSelectedName = [];
        foreach ($meds as $key => $medName) {
          foreach ($medSelected as $medKey) {
            if($key === $medKey){
              $medSelectedName[] = $medName;
            }
          }
        }   
        return implode('<br> &emsp;', $medSelectedName);
    }

  public function getProgName(){
      $progs = $this->getItemProg();
      $progSelected = explode(',', $this->progress);
      $progSelectedName = [];
      foreach ($progs as $key => $progName) {
        foreach ($progSelected as $progKey) {
          if($key === $progKey){
            $progSelectedName[] = $progName;
          }
        }
      }   
      return implode('<br> &emsp;', $progSelectedName);
  }

  public function getOrderName(){
    $orders = $this->getItemOrder();
    $orderSelected = explode(',', $this->oneday_list);
    $orderSelectedName = [];
    foreach ($orders as $key => $orderName) {
      foreach ($orderSelected as $orderKey) {
        if($key === $orderKey){
          $orderSelectedName[] = $orderName;
        }
      }
    }   
    return implode('<br> &emsp;', $orderSelectedName);
  }

  public function getOnedayName(){
    $orders = $this->getItemOrder();
    $orderSelected = explode(',', $this->oneday_list);
    $orderSelectedName = [];
    foreach ($orders as $key => $orderName) {
      foreach ($orderSelected as $orderKey) {
        if($key === $orderKey){
          $orderSelectedName[] = $orderName;
        }
      }
    }   
    return implode(' , ', $orderSelectedName);
  }

  /**
     * Gets query for [[Profile]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProfile()
    {
        return $this->hasOne(Profile::className(), ['user_id' => 'user_id']);
    }

    public function getAdmission()
    {
        return $this->hasOne(Admission::className(), ['an' => 'an']);
    }

    public function getWard()
    {
        return $this->hasOne(Ward::className(), ['ward_id' => 'ward_id']);
    }

    public function getPatientName(){
      return $this->admission->pname.$this->admission->fname.' '.$this->admission->lname;
    }

}

controllers/OrdersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Orders;
use app\models\OrdersSearch;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Admission;
use app\models\Office;
use kartik\mpdf\Pdf;
use app\models\OrderOneday;
use app\models\Setting;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Orders where AN .
     * @return mixed
     */
    public function actionDetail($id)
    {
        $order = Setting::find()->where(['config_name'=>'order_sort'])->one();
        if($order->config_value =='desc'){
            $model = Orders::find()->where(['an'=>$id])->orderBy(['order_id' => SORT_DESC])->all();
        } else {
            $model = Orders::find()->where(['an'=>$id])->orderBy(['order_id' => SORT_ASC])->all();
        }
        $ward = Admission::find()->where(['an'=>$id])->one();
        $an = $id;
        return $this->render('list', [
            'model' => $model,
            'an' => $an,
            'ward' =>$ward,
            'order' => $order,
        ]);
    }

    public function actionSwitchsort($id)
    {
        $layout = Setting::find()->where(['config_name'=>'order_sort'])->one();
        if ($layout->config_value == 'asc'){
            $layout->config_value = 'desc';
            $layout->save();
        } else {
            $layout->config_value = 'asc';
            $layout->save();
        }
        return $this->redirect(['detail','id' => $id]);

    }

    /**
     * Lists all Orders where AN .
     * @return mixed
     */
    public function actionPrint($id)
    {
        $model = Orders::find()->where(['an'=>$id])->all();
        $pt = Admission::find()->where(['an'=>$id])->one();
        $total = Orders::find()->where(['an'=>$id])->count();
        $office = Office::find()->one();

        $content = $this->renderPartial('_print',[
            'model' => $model,
            'pt' => $pt,
            'total' => $total,
            'office' => $office,
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'Doctor Order : '.$id],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        return $pdf->render();

    }

    /**
     * Lists all Orders where AN .
     * @return mixed
     */
    public function actionOrder($id)
    {
        $order = $this->findModel($id);
        $pt = Admission::find()->where(['an'=>$order->an])->one();
        $office = Office::find()->one();

        $content = $this->renderPartial('_order',[
            'order' => $order,
            'pt' => $pt,
            'office' => $office,
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'Doctor Order : '.$id],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        return $pdf->render();

    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Orders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Orders();
        $total = Orders::find()->where(['an'=>$id])->count();
        $model->an = $id;
        $model->user_id = Yii::$app->user->identity->id;
        $admit =  Admission::find()->where(['an' =>$id])->one();
        if($admit->ward_id){
            $model->ward_id = $admit->ward_id;
        }

        if ($model->load(Yii::$app->request->post())) {
            if($model->oneday_list){
                foreach($model->oneday_list as $order => $ordercode) 
                {
                    $r = OrderOneday::findOne($ordercode);
                    $model->is_lab ='0';
                    $model->is_xray ='0';
                    if($r->order_group_id == 'x') { $model->is_xray = '1'; }
                    if($r->order_group_id == 'l') { $model->is_lab = '1'; }
                }    
            }
            $model->save();
            return $this->redirect(['detail', 'id' => $id]);
        }

        return $this->render('create', [
            'model' => $model,
            'total' => $total,
        ]);
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        $model->medToArray();
        $model->progressToArray();
        $model->orderToArray();
        $total = Orders::find()->where(['an'=>$id])->count();

        if ($model->load(Yii::$app->request->post())) {
            if($model->oneday_list){
                foreach($model->oneday_list as $order => $ordercode) 
                {
                    $r = OrderOneday::findOne($ordercode);
                    $model->is_lab ='0';
                    $model->is_xray ='0';
                    if($r->order_group_id == 'x') { $model->is_xray = '1'; }
                    if($r->order_group_id == 'l') { $model->is_lab = '1'; }
                }    
            }
            $model->save();
            return $this->redirect(['detail', 'id' => $model->an]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'total' => $total,
            ]);
        }
    }

    /**
     * Deletes an existing Orders model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/orders/_order.php
<?php
use yii\helpers\Html;
use app\models\Admission;

?>
<h3 align="center"><?= $office->hospname ?>
<br><?= $office->address ?> <?= $office->zipcode ?><br>
Doctor Orders Sheet & Progress Note</h3>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
  <tr>
    <td width="35%"><b>&emsp; ชื่อ-สกุล </b><br>&emsp; &emsp; &emsp;<?= $pt->getPatientName() ?></td>
    <td width="25%"><b>&emsp;Ward </b> <?= $order->ward->ward_name ?><br>&emsp; <b>Bed</b> <?= $pt->bed ?></td>
    <td width="20%">&emsp; <b>อายุ</b> <?= $pt->age ?> ปี<br>&emsp; <b>น้ำหนัก </b> <?= $pt->vitalsign->bw ?> กก.</td>
    <td width="20%">&emsp; <b>HN:</b> <?= $pt->hn ?><br>&emsp; <b>AN:</b> <?= $pt->an ?></td>
  </tr>
</table>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
<tr>
  <th width="24%">Progress Note</th>
  <th width="28%">Order One Day</th>
  <th width="28%">Order Continue</th>
  <th width="20%">หมายเหตุ</th>
</tr>
<tr><td height=700 valign=top>
&emsp; <?= Admission::getThaiDateTime($order->order_datetime) ?><br>

&emsp; <?= $order->progress_note ?><br>
&emsp; <?= $order->progress ? $order->getProgName():''; ?><br><br><br><br />
&emsp; <?= $order->profile->fullname ?><br>
&emsp; <?= $order->profile->position ?><br>
&emsp; <?= $order->profile->license_no ?><br>
<td valign=top>
&emsp;<?= $order->oneday_list ? $order->getOrderName():''; ?><br>
<?= $order->order_oneday ?>
<td valign=top>
<?= $order->food == '2' ? '&emsp; [ / ] Soft Diet <br>' : '' ?>
<?= $order->food == '1' ? '&emsp; [ / ] Regular Diet <br>':'' ?>
<?= $order->record_i_o ? '&emsp; [ / ] Record I/O <br>' : '' ?> 
<?= $order->record_vitalsign ? '&emsp; [ / ] Record V/S <br>' : '' ?> 
<u>Medication</u><br>
&emsp;<?= $order->medName ?><br>
<u>Order เพิ่มเติม</u> <br>
<?= nl2br($order->order_continue) ?>
</td>
<td style="vertical-align:top">
<?= $order->comment ?>
</td>
</tr>
</table>
<hr>

views/orders/_print.php
<?php
use yii\helpers\Html;
use app\models\Admission;

function thaimonth($m){
  switch($m){
    case '01':$thainame = 'มกราคม';break;
    case '02':$thainame = 'กุมภาพันธ์';break;
    case '03':$thainame = 'มีนาคม';break;
    case '04':$thainame = 'เมษายน';break;
    case '05':$thainame = 'พฤษภาคม';break;
    case '06':$thainame = 'มิถุนายน';break;
    case '07':$thainame = 'กรกฎาคม';break;
    case '08':$thainame = 'สิงหาคม';break;
    case '09':$thainame = 'กันยายน';break;
    case '10':$thainame = 'ตุลาคม';break;
    case '11':$thainame = 'พฤศจิกายน';break;
    case '12':$thainame = 'ธันวาคม';break;
  }  
  return $thainame;
}
?>
<?php 
  $page=1;
  $row = 0;
  foreach($model as $order) {
    if($page <> 1 && $row%2 == 1 && $row > 2 || $row ==1 ){
      echo '<pagebreak>';
      $page++;
    }
    $row++;
    // echo '- '.$page.' - '.$row;
?>
<?php 
if($page == 1 || $row%2 == 0) {
?>
  <h3 align="center"><?= $office->hospname ?><br><?= $office->address ?> <?= $office->zipcode ?>
  <br>Doctor Orders Sheet & Progress Note</h3>  
<?php 
}
?>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
  <tr>
<?php 
  if($page == 1 || $row%2 == 0){
?>
    <td width="35%"><b>&emsp; ชื่อ-สกุล </b><br>&emsp; &emsp; &emsp;<?= $pt->getPatientName() ?></td>
    <td width="25%"><b>&emsp;Ward </b> <?= $order->ward->ward_name ?><br>&emsp; <b>Bed</b> <?= $pt->bed ?></td>
    <td width="20%">&emsp; <b>อายุ</b> <?= $pt->age ?> ปี<br>&emsp; <b>น้ำหนัก </b> <?= $pt->vitalsign->bw ?> กก.</td>
    <td width="20%">&emsp; <b>HN:</b> <?= $pt->hn ?><br>&emsp; <b>AN:</b> <?= $pt->an ?></td>
<?php 
  } else {
    echo '<td colspan="4"><b>&emsp;Ward </b>'.$order->ward->ward_name.' &emsp; <b>Bed</b> '.$pt->bed.'</td>';
  } 
?>
  </tr>
</table>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
<tr>
  <th width="25%">Progress Note</th>
  <th width="25%">Order One Day</th>
  <th width="35%">Order Continue</th>
  <th width="15%">หมายเหตุ</th>
</tr>
<tr>
<?php if($row == 1){
  echo '<td height=720 valign=top>';
}else{
  echo '<td height=350 valign=top>';
}
?>
&emsp;<?= Admission::getThaiDateTime($order->order_datetime) ?><br>
&emsp;<?= $order->progress ? $order->getProgName():''; ?><br>
&emsp;<?= nl2br($order->progress_note) ?><br>
&emsp;&emsp;<?= $row === 1 ?  Html::img(Yii::getAlias('@app').'/web/images/lung_clear.png', ['width' => 100]):''; ?><br>
<?= $order->profile->fullname ?><br>
<?= $order->profile->position ?><br>
<?= $order->profile->license_no ?>
<td valign=top>
&emsp;<?= $order->oneday_list ? $order->getOrderName():''; ?><br>
<?= nl2br($order->order_oneday) ?>
<td valign=top>
<?= $order->food == '2' ? '&emsp; [ / ] Soft Diet <br>' : '' ?>
<?= $order->food == '1' ? '&emsp; [ / ] Regular Diet <br>':'' ?>
<?= $order->record_i_o ? '&emsp; [ / ] Record I/O <br>' : '' ?> 
<?= $order->record_vitalsign ? '&emsp; [ / ] Record V/S <br>' : '' ?> 
<?= $order->medName ?  '<u>Medication</u><br>&emsp;'.$order->medName .'<br>':'' ?>
<?= $order->order_continue? '<u>Order เพิ่มเติม</u> <br>'.nl2br($order->order_continue):'' ?>
</td>
<td style="vertical-align:top">
<?= $order->comment ?>
</td>
</tr>
</table>
<?php 

} ?>

views/orders/list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Admission;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AdmissionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Doctor Order AN:'.$an.' ชื่อ-สกุล:'.$ward->getPatientName();
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="admission-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= !$ward->dsch ? Html::a('เพิ่ม Order', ['create','id'=>$an], ['class' => 'btn btn-success']):'' ?>
        &emsp; 
        <?= $order->config_value == 'asc' ? Html::a('เรียง Z > A', ['switchsort','id' => $an], ['class' => 'btn btn-primary']):Html::a('เรียง A > Z', ['switchsort','id' => $an], ['class' => 'btn btn-primary']); ?> 
        &emsp; 
        <?= Html::a('Vital Sign', ['notes/vitalsign','id'=>$an], ['class' => 'btn btn-info']) ?>
        &emsp; 
        <?= Html::a('ดูบันทึกทางการพยาบาล ', ['notes/detail','id'=>$an], ['class' => 'btn btn-info']) ?>
        &emsp; 
        <?= Html::a('พิมพ์ Doctor Order', ['print','id'=>$an], ['class' => 'btn btn-warning']) ?>
        &emsp; &emsp; 
        <?= Html::a('กลับไปหน้าหลัก', ['admission/index','id'=>$ward->ward_id], ['class' => 'btn btn-danger']) ?>
    </p>

<table width="100%" border="1">
<tr>
<th width="20%" style="text-align:center">Progress Note</th>
<th width="35%" style="text-align:center">Order One Day</th>
<th width="35%" style="text-align:center">Order Continue</th>
<th width="10%" style="text-align:center">หมายเหตุ</th>
</tr>
<?php
if($model){
    foreach($model as $order){
?>
<tr>
<td style="vertical-align:top">
&emsp; <?= Admission::getThaiDateTime($order->order_datetime) ?><br>
&emsp;<?= $order->progress ? $order->getProgName():''; ?><br>
&emsp; <?= nl2br($order->progress_note) ?><br><br>
&emsp; <?= $order->profile->fullname ?><br>
&emsp; <?= $order->profile->position ?><br>
&emsp; <?= $order->profile->license_no ?><br>
</td>
<td style="vertical-align:top">
&emsp;<?= $order->oneday_list ? $order->getOrderName():''; ?><br>
<?= nl2br($order->order_oneday) ?></td>
<td style="vertical-align:top">
<?= $order->food == '2' ? '&emsp; [ / ] Soft Diet <br>' : '' ?>
<?= $order->food == '1' ? '&emsp; [ / ] Regular Diet <br>':'' ?>
<?= $order->record_i_o ? '&emsp; [ / ] Record I/O <br>' : '' ?> 
<?= $order->record_vitalsign ? '&emsp; [ / ] Record V/S <br>' : '' ?> 
<?= $order->medName ?  '<u>Medication</u><br>&emsp;'.$order->medName .'<br>':'' ?>
<?= $order->order_continue? '<u>Order เพิ่มเติม</u> <br>'.nl2br($order->order_continue):'' ?>
</td>
<td style="vertical-align:top">
    &ensp;<?= ((Yii::$app->user->identity->id == $order->user_id ) && (!$ward->dsch)) ? Html::a('แก้ไข Order', ['update', 'id' => $order->order_id], ['class' => 'btn btn-warning']):'' ?><br>
    &ensp;<?= Html::a('พิมพ์ Order', ['order', 'id' => $order->order_id], ['class' => 'btn btn-info']) ?><br><br />
    <?= $order->comment ?>
</td>
</tr>
<?php
    }
}
?>
</table>
<br>
<div style="text-align:center"> 
        <?= !$ward->dsch ? Html::a('Discharge คนไข้', ['admission/dc','id' => $an], ['class' => 'btn btn-danger','style'=>'width:200px']):'' ?>
</div>
</div>